version: '3.8'

networks:
  inception_network:

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: "/Users/${USER}/data"
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: "/Users/${USER}/data"
      o: bind

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost"]
      interval: 10s
      timeout: 3s
      retries: 3
    # depends_on:
    #   wordpress:
    #     condition: service_healthy
    ports:
      - "443:443"
    volumes:
      - wordpress:/usr/share/nginx/html
    networks:
      - inception_network

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception_network

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "pgrep", "php-fpm"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_network
