version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - nginx:/etc/nginx
    networks:
      - inception

volumes:
  db:
  wordpress:
  nginx:

networks:
  inception:
