version: '3.8'

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: "/home/${USER}/data/mariadb"
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: "/home/${USER}/data/wordpress"
      o: bind

networks:
  inception:

services:
  nginx:
    build: requirements/nginx/.
    ports:
      - "443:443"
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/html
    networks:
      inception:
  wordpress:
    build: requirements/wordpress/.
    healthcheck:
      test: ["CMD", "pgrep", "php-fpm"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      nginx:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/html
    networks:
      inception:
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
      - WORDPRESS_TEST_USER=${WORDPRESS_TEST_USER}
      - WORDPRESS_TEST_USER_PASSWORD=${WORDPRESS_TEST_USER_PASSWORD}
      - WORDPRESS_TEST_USER_EMAIL=${WORDPRESS_TEST_USER_EMAIL}
  mariadb:
    build: requirements/mariadb/.
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/mysql
    networks:
      inception:
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
