version: '3.8'

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: "/Users/${USER}/data/mariadb"
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: "/Users/${USER}/data/wordpress"
      o: bind

networks:
  inception:


services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      wordpress:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/html
    networks:
      inception:
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    healthcheck:
      test: ["CMD", "pgrep", "php-fpm"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/html
    networks:
      inception:
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/mysql
    networks:
      inception:
